# Config file for automatic testing at travis-ci.org
sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
dist: xenial

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install tox travis-tox
  - pip install -r requirements.txt -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox

after_success:
  - codecov
