# Config file for automatic testing at travis-ci.org
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install: pip install travis-tox tox
dist: xenial
sudo: false
script: tox
after_success:
  - codecov
